import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Banner from '../components/banner'
import Card from '../components/card'
import coffeeStores from '../data/coffee-stores.json'

const handleOnBtn = () => {
  console.log("ok it's work")
}

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner 
                buttonText="View stores bearby" 
                handleOnClick={handleOnBtn}
          />

        <div className={styles.heroImage}>
        <Image src="/static/hero-image.png" 
        width={700} height={400}
        alt="hero img"
        />
        </div>

      <div className={styles.cardLayout}>
        {coffeeStores.map(coffeeStores=>{
          return ( 
                 <Card 
                    key={coffeeStores.id} //solution for "Warning: Each child in a list should have a unique “key” prop." message
                    name={coffeeStores.name}
                    imURL={coffeeStores.imgUrl}
                    href={`/coffee-store/${coffeeStores.id}`}
                    className={styles.card}
                  />)
        })}
      </div>
      </main>
    </div>
  )
}
