import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Banner from '../components/banner'
import Card from '../components/card'
import coffeeStoresData  from '../data/coffee-stores.json'

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores:coffeeStoresData ,
    }, // will be passed to the page component as props
  };
}


const handleOnBtn = () => {
  console.log("ok it's work")
}

export default function Home(props) {

  console.log("props is", props);


  return (
    <div className={styles.container}>

      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner 
                buttonText="View stores bearby" 
                handleOnClick={handleOnBtn}
          />

        <div className={styles.heroImage}>
        <Image src="/static/hero-image.png" 
        width={700} height={400}
        alt="hero img"
        />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
      <h2 className={styles.heading2}>Toronto stores</h2>
      <div className={styles.cardLayout}>
        {props.coffeeStores.map(coffeeStores=>{
          return ( 
                 <Card 
                    key={coffeeStores.id}
                    name={coffeeStores.name}
                    imURL={coffeeStores.imgUrl}
                    href={`/coffee-store/${coffeeStores.id}`}
                    className={styles.card}
                  />)
        })}
      </div>
      </>)}
      </main>
    </div>
  )
}
